cloud_config_path="secure-connect-aman.zip"
cassandra_uname="FlCmOCjmAlhJDBqkgmoqfeRC"
cassandra_password="LKjWvmoOg86ZZwlnD1MJNr4,P0HhRA+pfp5fwfb-7E8ojedQ,toug8zSLUgPxm-37jj1yteXTfDPZM,wCcYoOY+fAhCMZYT7jU7dL6vK57i+z4JnT8F7+fjRpeazQCh8"
keyspace_name="adm"
table_name="admadm"